version: "3"

x-env: &env
  DATABASE_URL: postgres://driverhub:1234@db:5432/driverhub

services:
  db:
    image: postgres
    volumes:
      - driverhub-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB:   driverhub
      POSTGRES_USER: driverhub
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile-rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      <<: *env
    volumes:
      - .:/driverhub
    ports:
      - "3000:3000"
    depends_on:
      - db
  api:
    build:
      context: .
      dockerfile: Dockerfile-node
    command: npm run dev
    volumes:
      - .:/nodeapi
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  driverhub-db:
    external: true
