version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: driverhub
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile-rails
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/driverhub
    ports:
      - "3000:3000"
    depends_on:
      - db
  api:
    build:
      context: .
      dockerfile: Dockerfile-node
    restart: always
    volumes:
      - .:/nodeapi
    ports:
      - "5000:5000"
    depends_on:
      - db
