
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: driverhub
  password: 1234
  host: db
  port: 5432

development:
  <<: *default
  database: driverhub_development

test:
  <<: *default
  database: driverhub_test

